# =========================
# SCREEN DIMENSIONS
# =========================

INFO_WIDTH = 400
MAP_WIDTH = 1080
DETAILS_WIDTH = 800

HEIGHT = 900

WIDTH = INFO_WIDTH + MAP_WIDTH
WIDTH_WITH_DETAILS = INFO_WIDTH + MAP_WIDTH + DETAILS_WIDTH

# =========================
# INFO PANEL LAYOUT
# =========================

HEADER_H = 64
INFO_GAP = 10

PLOT_TOP_GAP = 0
PLOT_Y = HEADER_H + INFO_GAP + PLOT_TOP_GAP
PLOT_H = 270

LIST_GAP = 0
LIST_Y = PLOT_Y + PLOT_H + LIST_GAP
LIST_H = 220

VEHICLE_Y = LIST_Y + LIST_H + 10
VEHICLE_H = 110

STATUS_GAP = 10
STATUS_Y = VEHICLE_Y + VEHICLE_H + STATUS_GAP
STATUS_H = 100

FOOTER_H = 120

ACTIONBAR_H = 60
ACTIONBAR_Y = HEIGHT - ACTIONBAR_H
